title: ChgkRating
description: Opinionated Ruby client for the competitive What? Where? When? rating WebAPI
theme: jekyll-theme-architect
markdown: kramdown
url: chgk-rating.bodrovis.tech
repository: bodrovis/ChgkRating
exclude:
  - Gemfile
  - Gemfile.lock