source "https://rubygems.org"

group :jekyll_plugins do
  gem "github-pages"
end
gem 'jekyll-theme-architect'

gem 'wdm', '>= 0.1.0' if Gem.win_platform?
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]