# frozen_string_literal: true

source 'https://rubygems.org'

group :jekyll_plugins do
  gem 'github-pages'
end
gem 'jekyll-theme-architect'

gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw jruby]
gem 'wdm', '>= 0.1.0' if Gem.win_platform?
